name: Email

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  ENV: production

jobs:
  build:

    runs-on: node-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: npm build --production
    - name: Run tests
      run: npm test
